from decouple import config
from django.utils.translation import gettext_lazy as _

from .configs import (
    DATABASE_CONFIG,
    MIDDLEWARE_CONFIG,
    INSTALLED_APPS_CONFIG,
    RECAPTCHA_CONFIG,
    EMAIL_CONFIG,
    BASE_CONFIG,
    JALALI_DATE_CONFIG,
    TEMPLATES_CONFIG,
    STATIC_CONFIG,
    MEDIA_CONFIG,
    AUTH_AND_SESSION_CONFIG,
    CKEDITOR_CONFIG,
    LANGUAGES_CONFIG,
    CELERY_and_CATCHING_CONFIG,
    CSP_CONFIG,
)

DEPLOYED = config("DEPLOYED", cast=bool, default=False)
SECRET_KEY = config(
    "SECRET_KEY", default="Test"
)  # secret key generator -> https://djecrety.ir/
DEBUG = config("DEBUG", cast=bool, default=True)
ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS", cast=lambda v: [i.strip() for i in v.split(",")], default="*"
)
USE_SQLITE_DB = config("USE_SQLITE_DB", cast=bool, default=True)
USE_MYSQL_DB_BINARY = config("USE_MYSQL_DB_BINARY", cast=bool, default=False)
USE_EMAIL_SERVICE = config("USE_EMAIL_SERVICE", cast=bool, default=False)
USE_SMS_SERVICE = config("USE_SMS_SERVICE", cast=bool, default=False)
USE_RECAPTCHA = config("USE_RECAPTCHA", cast=bool, default=False)
USE_SSL_CONFIG = config("USE_SSL_CONFIG", cast=bool, default=False)
USE_ALLAUTH_SERVICE = config("USE_ALLAUTH_SERVICE", cast=bool, default=False)

if not USE_SQLITE_DB and USE_MYSQL_DB_BINARY:
    import pymysql

    pymysql.install_as_MySQLdb()

INSTALLED_APPS = INSTALLED_APPS_CONFIG.INSTALLED_APPS

MIDDLEWARE = MIDDLEWARE_CONFIG.MIDDLEWARE

ROOT_URLCONF = "_0_config.urls.urls"

TEMPLATES = TEMPLATES_CONFIG.TEMPLATES

JALALI_DATE_DEFAULTS = JALALI_DATE_CONFIG.JALALI_DATE_DEFAULTS

WSGI_APPLICATION = "_0_config.wsgi.application"

AUTH_USER_MODEL = "_1_user.User"

DATABASES = DATABASE_CONFIG.DATABASES

SIMPLE_HISTORY_HISTORY_CHANGE_REASON_USE_TEXT_FIELD = True

AUTH_PASSWORD_VALIDATORS = AUTH_AND_SESSION_CONFIG.AUTH_PASSWORD_VALIDATORS

if USE_ALLAUTH_SERVICE:
    AUTHENTICATION_BACKENDS = AUTH_AND_SESSION_CONFIG.AUTHENTICATION_BACKENDS
    SOCIALACCOUNT_PROVIDERS = AUTH_AND_SESSION_CONFIG.SOCIALACCOUNT_PROVIDERS
    LOGIN_REDIRECT_URL = AUTH_AND_SESSION_CONFIG.LOGIN_REDIRECT_URL
    LOGOUT_REDIRECT_URL = AUTH_AND_SESSION_CONFIG.LOGOUT_REDIRECT_URL
    SOCIALACCOUNT_LOGIN_ON_GET = AUTH_AND_SESSION_CONFIG.SOCIALACCOUNT_LOGIN_ON_GET
    ACCOUNT_SIGNUP_FIELDS = AUTH_AND_SESSION_CONFIG.ACCOUNT_SIGNUP_FIELDS

LOGIN_URL = "/v1/auth/login/"

# Session Age
REMEMBER_ME_DURATION = AUTH_AND_SESSION_CONFIG.REMEMBER_ME_DURATION
SESSION_COOKIE_AGE = AUTH_AND_SESSION_CONFIG.SESSION_COOKIE_AGE

if LANGUAGES_CONFIG.USE_MULTI_LANGUAGE:
    LANGUAGES = LANGUAGES_CONFIG.LANGUAGES
    LANGUAGES_DIRECTION = LANGUAGES_CONFIG.LANGUAGES_DIRECTION

# ##### CODE SETTING BASE ##### #
LANGUAGE_CODE = BASE_CONFIG.LANGUAGE_CODE
TIME_ZONE = BASE_CONFIG.TIME_ZONE
USE_I18N = BASE_CONFIG.USE_I18N
USE_TZ = BASE_CONFIG.USE_TZ

# ##### THUMBNAIL SETTING BASE ##### #
THUMBNAIL_FORCE_OVERWRITE = True

# ##### AUTO FIELD BASE ##### #
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = MEDIA_CONFIG.MEDIA_ROOT

# ##### MEDIA VARIABLE BASE ##### #
MEDIA_URL = MEDIA_CONFIG.MEDIA_URL

# ##### STATIC VARIABLE BASE ##### #
STATIC_URL = STATIC_CONFIG.STATIC_URL
STATICFILES_DIRS = STATIC_CONFIG.STATICFILES_DIRS
STATICFILES_STORAGE = STATIC_CONFIG.STATICFILES_STORAGE

if DEPLOYED:
    STATIC_ROOT = STATIC_CONFIG.STATIC_ROOT

if USE_EMAIL_SERVICE:
    EMAIL_BACKEND = EMAIL_CONFIG.EMAIL_BACKEND
    EMAIL_HOST = EMAIL_CONFIG.EMAIL_HOST
    EMAIL_PORT = EMAIL_CONFIG.EMAIL_PORT
    EMAIL_HOST_USER = EMAIL_CONFIG.EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD = EMAIL_CONFIG.EMAIL_HOST_PASSWORD
    EMAIL_USE_TLS = EMAIL_CONFIG.EMAIL_USE_TLS
    EMAIL_USE_SSL = EMAIL_CONFIG.EMAIL_USE_SSL
    DEFAULT_FROM_EMAIL = EMAIL_CONFIG.DEFAULT_FROM_EMAIL

if USE_SMS_SERVICE:
    SMS_SERVICE_KEY = config("SMS_SERVICE_KEY")

if USE_RECAPTCHA:
    RECAPTCHA_PUBLIC_KEY = RECAPTCHA_CONFIG.RECAPTCHA_PUBLIC_KEY
    RECAPTCHA_PRIVATE_KEY = RECAPTCHA_CONFIG.RECAPTCHA_PRIVATE_KEY

if DEPLOYED:
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    CORS_ALLOWED_ORIGINS = config(
        "CORS_ALLOWED_ORIGINS", cast=lambda v: [i.strip() for i in v.split(",")]
    )
    CSRF_TRUSTED_ORIGINS = config(
        "CSRF_TRUSTED_ORIGINS", cast=lambda v: [i.strip() for i in v.split(",")]
    )
    if USE_SSL_CONFIG:
        # Https settings
        SESSION_COOKIE_SECURE = True
        SESSION_COOKIE_HTTPONLY = True
        CSRF_COOKIE_SECURE = True
        SECURE_SSL_REDIRECT = True

        # HSTS settings
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_PRELOAD = True
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True

        # more security settings
        SECURE_CONTENT_TYPE_NOSNIFF = True
        # SECURE_BROWSER_XSS_FILTER = True
        X_FRAME_OPTIONS = "SAMEORIGIN"
        SECURE_REFERRER_POLICY = "strict-origin"
        USE_X_FORWARDED_HOST = True
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CORS_ORIGIN_ALLOW_ALL = config("CORS_ORIGIN_ALLOW_ALL", cast=bool, default=False)

CKEDITOR_5_UPLOAD_FILE_TYPES = CKEDITOR_CONFIG.CKEDITOR_5_UPLOAD_FILE_TYPES
CKEDITOR_5_CONFIGS = CKEDITOR_CONFIG.CKEDITOR_5_CONFIGS

CELERY_BROKER_URL = CELERY_and_CATCHING_CONFIG.CELERY_BROKER_URL

CACHES = CELERY_and_CATCHING_CONFIG.REDIS_CACHES

SECURE_CSP = CSP_CONFIG.SECURE_CSP
